### ISSUE TITLE
OM URL should be put in an ansible variable

### ISSUE THREAD

**Issue by emisca** [HenryGP/om_ansible#66]
The code:
```
  tasks:
    - name: Set Ops Manager URL for http
      set_fact:
        om_url: "http://omserver:8080"
      when: not om_https
    - name: Set Ops Manager URL for https
      set_fact:
        om_url: "https://omserver:8443"
      when: om_https
```

is repeated in ansible files many times, we should put this once in the vars yaml file.
